examples/tv-casting-app/android/README.md
scripts/build/build/targets.py
scripts/build/builders/android.py

The no-debug target significantly reduces the size of the binaries

Adding a no-debug target into the tv apps

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CommissionableDataProviderImpl.mm

We need to define the variables since they are scoped out due to the test flag not being set

Darwin fix

---

examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DiscoveredNodeData.java

Adding defensive null checks on serviceInfo.attributes returned by the NsdManager before dereferencing them
Tested with the Android tv-casting-app running against the Linux tv-app

Android tv-casting-app: Adding defensive null checks in DiscoveredNodeData constructor

---

examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CommissionerDiscoveryDelegateImpl.h
examples/tv-casting-app/darwin/TvCasting/TvCasting/CertTestView.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/CertTestViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/CommissioningView.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/MediaPlaybackViewModel.swift

Fixes #25023 on the v1.0.0 branch.
---
Lock the SDK before interacting with it.
[Problem]
The Matter SDK assumes that the client will take a lock on the SDK prior to
interacting with any APIs. There is 1 Android function and several iOS functions
that do not take the lock prior to interacting with the SDK APIs.
There are also some functions that invoke the Matter SDK in a way that may
result in out-of-order callback invocation (e.g. the conceptual "started"
callback may be invoked after the conceptual "ended" callback).
[Solution]
Create utility functions that help ensure that the Matter SDK is invoked safely
and that callbacks are delivered in the correct order.
[Testing]
Performed local, manual testing with the 'tv-casting-app' example on iOS against
a Raspberry Pi running the 'tv-app'. …

V1.0.0 branch 25023 fix

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/CommissionerDiscoveryFragment.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java
examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp
examples/tv-casting-app/android/App/app/src/main/res/layout/fragment_commissioner_discovery.xml
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/TvCasting/TvCasting/StartFromCacheView.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/StartFromCacheViewModel.swift
examples/tv-casting-app/tv-casting-common/include/CastingServer.h
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp
examples/tv-casting-app/tv-casting-common/src/PersistenceManager.cpp

A client app may want to have an ability to clear the list of video players previously connected to, say in the case a user signs out and a different user has to sign in. The Matter Tv Casting library should expose a way to purge the cache
1. Exposed APIs in the libraries for Android, iOS and common to PurgeCache
2. Added buttons to the Android and iOS tv-casting-app to Purge the cache.
Tested using the Android / iOS tv-casting-apps running against a Linux tv-app

tv-casting-app: Allow for a way for Matter TV casting cache to be purged

---

src/app/CASESessionManager.h
src/app/server/Server.cpp

Fixes the root cause of #25023
[Problem]
The Server::Shutdown API releases resources in the reverse order in which they were allocated. Unfortunately, there is a cyclic dependency between the ExchangeMgr, which is released first, and the SessionManager, which contains one or more Sessions that may need to release ExchangeContexts. If an ExchangeContext is awaiting a response when it is aborted, it uses the (now-null) ExchangeMgr for cleanup, resulting in a segmentation fault.
[Solution]
Shut down the SessionManager before the ExchangeMgr. While counter-intuitive and somewhat of an anti-pattern, this ensures that the necessary resources are available for the SessionManager to shut down. The ExchangeMgr shutdown process has relatively few side effects and is currently safe to defer. …

Safely dispose of resources on Server Shutdown

---

examples/tv-casting-app/tv-casting-common/include/CastingServer.h
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp

On some devices it appears that the commissioner may not have an appropriate IPV6 address and attempts to send a user directed commissioning request to a device using its IPV6 address.
Its a bit unclear how this situation happens but in theory it could occur. In most cases this should be safe to default to an ipv4 address if it is available.
The implementation of the user directed commissioning server does something similar.

Default to use an IPV4 address

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge.xcodeproj/project.pbxproj
examples/tv-casting-app/darwin/MatterTvCastingBridge/strip_debug_symbols.sh

The libTvCastingApp.a file was ~110mb prior to this strip operation, afterwards it dropped to ~21mb.
I also fixed the release target so that it woudl build.
Tested this by seeing the drop on an XCode build and also verifying the TVapp still functions as before

Adding in build step to strip debug symbols

---

examples/tv-casting-app/tv-casting-common/include/CastingServer.h
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp

numIPs in Resolver.h: https://github.com/project-chip/connectedhomeip/blob/master/src/lib/dnssd/Resolver.h#L46 is defined as a size_t. It'd be easier going forward if similar data members in the tv-casting app code use the same data type (like mTargetVideoPlayerNumIPs) - hence this change.
Built and Tested with the Android tv-casting-app

Reverting to using size_t for numIPs

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/ConnectionFragment.java

Clicking connect in the tv-casting-app freezes the UI for a few seconds because it tries to attempt the connection on the UI thread. This puts it in an async thread so that the UI is not blocked while its trying to establish that connection.
Tested by attempting the connection and verifying it wasn't paused and still showed the right messages and connected successfully.

Take connection operations off the UI thread

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/MainActivity.java
examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/util/DACProviderStub.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/AppParameters.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java
examples/tv-casting-app/android/BUILD.gn
examples/tv-casting-app/android/args.gni
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/AppParameters.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsHolder.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsHolder.m
examples/tv-casting-app/darwin/TvCasting/TvCasting.xcodeproj/project.pbxproj
examples/tv-casting-app/darwin/TvCasting/TvCasting/CommissioningViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/ExampleDAC.swift
examples/tv-casting-app/darwin/args.gni
examples/tv-casting-app/linux/args.gni
src/credentials/BUILD.gn

So far, the DAC Provider/Holder had to be set in the calls to init the tv-casting libraries on Android/iOS. This change decouples setting the DAC Provider/Holder so that it can be set lazily by a client app.
Built and Tested the Android/iOS tv-casting-app with the Linux tv-app

tv-casting-app: Decouple setDAC* API from tv-casting initialization

---

src/protocols/user_directed_commissioning/UserDirectedCommissioningClient.cpp

The Matter spec says it may send up to 4 retries (5 total) for UDC at least 100ms apart. However, so far the delay in the SDK for each request was 1 second - this delays the subsequent on-network commissioning process by 5+ seconds. This PR reduces that delay (per UDC request) to the minimum delay prescribed by the spec. This should help reduce the cumulative delay from 5 sec to 500ms.
Tested using the Android tv-casting-app sending UDC requests to the Linux tv-app

Reducing delay between UDC requests to 100ms

---

examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp
examples/tv-casting-app/android/args.gni

The AndroidAppServerWrapper in the core SDK defaults to setting the ExampleDACProvider per https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/java/AndroidAppServerWrapper.cpp#L59-L62
In this change, we allow the Android tv-casting app setDACProvider  API to reset the DAC Provider. Also, since the AndroidAppServerWrapper requires the ExampleDACProvider, we need to allow building of the example credentials (that is let chip_build_example_creds default to true)

Android tv-casting-app: Allowing RE-setting DACProvider

---

src/platform/android/java/chip/platform/NsdServiceFinderAndResolver.java

On my network, the service type resolved with an extra `.` at the front (`._matterc._udp`) even though the requested service type was `_matterc._udp`. This is impactful because internally we do a check for the length of the service type and it has to match the max length (13). In this case because of the extra "." the check fails.
I've changed this to just use the ServiceInfo we used to start the resolution with so that there is no contention here.
With this change I was able to successfully commission, without it, commissioning failed.

Use TargetServiceInfo to resolve the ServiceType

---

examples/tv-casting-app/linux/args.gni

This change defaults to leaving chip_build_example_creds set to true because the linux tv-casting-app uses the Example DAC classes: https://github.com/sharadb-amazon/connectedhomeip/blob/master/examples/tv-casting-app/linux/main.cpp#L128
Without this, the build was failing with the following error: 
```
2023-03-14 13:07:31 INFO    /__w/connectedhomeip/connectedhomeip/out/linux-x64-tv-casting-app/../../examples/tv-casting-app/linux/third_party/connectedhomeip/examples/chip-tool/commands/example/ExampleCredentialIssuerCommands.h:38: undefined reference to `chip::Credentials::Examples::GetExampleDACProvider()'
2023-03-14 13:07:31 INFO    /usr/bin/ld: obj/chip-tv-casting-app.main.cpp.o: in function `main':
2023-03-14 13:07:31 INFO …
```

Including ExampleDACs for linux/tv-casting-app

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/TvCasting/TvCasting/CertTestViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/CommissionerDiscoveryViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/CommissioningViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/ContentLauncherViewModel.swift
examples/tv-casting-app/darwin/TvCasting/TvCasting/TvCastingApp.swift

There were a few APIs on iOS created early on that were returning a bool to indicate success / failure of a casting command, while the newer APIs were returning a MatterError object which is better for debuggability because it has an error code and an error message. In this change, we bring the old APIs up to speed and have them return MatterError objects as well.
Built, commissioned and cast with the iOS tv-casting-app against a Linux tv-app

iOS tv-casting-app: Switching responses from Bools to MatterErrors on inital APIs

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/util/DACProviderStub.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/DACProvider.java
examples/tv-casting-app/android/App/app/src/main/jni/cpp/JNIDACProvider.cpp
examples/tv-casting-app/android/App/app/src/main/jni/cpp/JNIDACProvider.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsHolder.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsHolder.m
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsProviderImpl.hpp
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/DeviceAttestationCredentialsProviderImpl.mm
examples/tv-casting-app/darwin/TvCasting/TvCasting/ExampleDAC.swift

It is best practice for private keys to not be available to the application layer in plain form. In fact you can generate keys within the secure element on device, or TrustZone, that is not extractable in plain form. In order to support such best practices, the change addresses this by modifying the DAC Provider's SignWithDeviceAttestationKey function that is provided by the example tv castin app to:
- For Android, ask the Java application layer to do the signing via the Android Keystore.
- For iOS, request the SecKeyRef for the private key as part of setting the DAC provider and hence allowing the SDK to just sign using the Security APIs.
> !!!!!!!!!! Please delete the instructions below and replace with PR description
>
> If you have an issue number, please use a syntax of
> `Fixes …

Enable TV Casting App Example to using Hardware-backed keys For DAC

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/MainActivity.java
examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/util/PreferencesConfigurationManager.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/AppParameters.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java

The Android TV Casting library does not allow the tv-casting client app to pass in its own version of the ConfigurationManager.
* Introduced an AppParameter that lets the tv-casting-app pass in its implementation of the ConfigurationManager.
* Copied the PreferencesConfigurationManager from https://github.com/project-chip/connectedhomeip/blob/master/src/platform/android/java/chip/platform/PreferencesConfigurationManager.java into the tv-casting-app and plugged that in as reference for the sample app
Tested that commissioning works when running an Android tv-casting-app against a Linux tv-app

android/tv-casting-app: Adding ConfigurationManager as AppParameter

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/MainActivity.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java

Two or more instances of the TvCastingApp could be initialized by client code,  that would end up sharing the same resources like the NsdManager or TvCastingApp-JNI, which could cause inconsistencies.
We are not synchronizing the execution of the discovery related code in discoverVideoPlayerCommissioners or stopVideoPlayerDiscovery which can lead to errors. Like the crash "listener not registered" if stopVideoPlayerDiscovery is called a second time before its first execution finishes.
* Made the TvCastingApp a singleton
* Synchronized discoverVideoPlayerCommissioners() and stopVideoPlayerDiscovery()
* Logged an error if we get an IllegalArgumentException (for  "listener not registered") on calling nsdManager.stopDiscovery()
Tested with the Android tv-casting-app and ensured discovery …

Making TvCastingApp singleton and synchronizing discovery code

---

examples/tv-casting-app/android/App/app/src/main/java/com/chip/casting/app/ConnectionFragment.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java
examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.cpp
examples/tv-casting-app/android/App/app/src/main/jni/cpp/TvCastingApp-JNI.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.h
examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/darwin/TvCasting/TvCasting/CommissioningViewModel.swift
examples/tv-casting-app/linux/CastingUtils.cpp
examples/tv-casting-app/tv-casting-common/include/CastingServer.h
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp

Sometimes a commissioner (TV) may **abandon** commissioning (different from erroring out) of the tv-casting-app midway through. If a failsafe was armed by the commissioner with a certain expiry time, in such a case, the tv-casting-app is unable to begin a new user directed commissioning session right away. This causes an undesirable CX where the customer may have to wait for the failsafe timer to expire (which can be too long, running longer than a minute).
In this change, before opening the commissioning window, we check if a failsafe is armed already. If it is, we force the failsafe timer to expire by calling ForceFailSafeTimerExpiry, wait for the kFailSafeTimerExpired event, and then attempt to open the commissioning window.
With this change, the Android tv-casting-app implements a …

Forcing FailSafe timer expiry when opening commisisoning window

---

examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/FailureCallback.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/MatterCallbackHandler.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SubscriptionEstablishedCallback.java
examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/SuccessCallback.java
examples/tv-casting-app/android/App/app/src/main/jni/cpp/MatterCallbackHandler-JNI.cpp
examples/tv-casting-app/android/App/app/src/main/jni/cpp/MatterCallbackHandler-JNI.h

On Android OS 8, we encountered the following errors (not seen before on other phones/versions of Android):
> 05-08 13:00:16.245 20360 20637 D SVR     : JNI_METHOD openBasicCommissioningWindow called with duration 60
05-08 13:00:16.245 20360 20637 D SVR     : CallbackBaseJNI::SetUp called
05-08 13:00:16.245 20360 20637 E SVR     : Failed to access 'handleInternal' method with signature (ILjava/lang/String;)V
05-08 13:00:16.245 20360 20637 D SVR     : CallbackBaseJNI::SetUp called
05-08 13:00:16.245 20360 20637 E SVR     : Failed to access 'handleInternal' method with signature (Ljava/lang/Object;)V
05-08 13:00:16.245 20360 20637 D SVR     : CallbackBaseJNI::SetUp called
05-08 13:00:16.245 20360 20637 E SVR     : Failed to access 'handleInternal' method with signature …

Android/tv-casting-app: Fix for issue in finding handleInternal() on some Android phones

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/chip_xcode_build_connector.sh

On iOS, there's a lot of crashes that are occurring when the app is terminated due to invalid CHIP state during termination. The reason these states are incorrect is because the iOS system already handle much of the termination logic itself. Hence, the underlying states are not in sync with the upper level states. This applies more specifically within the ObjectLifeCycle logic. The fix disables the C++ static destructors on exit. This prevents the app from crashing when it's already terminated.

Disable c++ static destructors on exit for iOS apps

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp

The iOS tv-casting-app can crash if ShutdownAllSubscriptions is called before initializeApp returns successfully. See crash below:
```
Crashed: com.apple.main-thread
0  libdispatch.dylib              0x3d118 dispatch_async$VARIANT$armv81 + 148
1  MatterTvCastingBridge          0x6a64 -[CastingServerBridge dispatchOnMatterSDKQueue:block:] + 344
2  MatterTvCastingBridge          0xcf78 -[CastingServerBridge shutdownAllSubscriptions:requestSentHandler:] + 196
3  PrimeVideo-Beta                0x42ac3c SecondScreenMatterSubscriptionManager.shutDownAllSubscriptions(removeAll:reason:) + 63 (SecondScreenMatterSubscriptionManager.swift:63)
4  PrimeVideo-Beta                0xb28f24 SecondScreenMatterContext.onAppWillResignActive() + 41 (SecondScreenMatterContext.swift:41)
5  PrimeVideo-Beta …
```

Adding defensive asserts in APIs to ensure CastingServer/Bridge is in the correct state

---

src/app/server/Dnssd.h

Without this fix, the build of the Android tv-casting-app fails with the following error since CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY was disabled.
```
../../examples/tv-casting-app/android/third_party/connectedhomeip/src/app/server/Dnssd.h:133:45: error: private field 'mTimeSource' is not used [-Werror,-Wunused-private-field]
2023-06-28 11:25:49 INFO        Time::TimeSource<Time::Source::kSystem> mTimeSource;
```
Moved the mTimeSource data member to be inside an #if CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY statement.
Build and ran the android tv-casting-app successfully after this change

Fixing build error due to unused mTimeSource

---

examples/tv-casting-app/darwin/MatterTvCastingBridge/MatterTvCastingBridge/CastingServerBridge.mm

This commit 2d5f022 introduced a way to time the discovery process out on the iOS tv-casting-app. However, it dispatched the cancelDiscoveryCommissionersWork on the clientQueue. This is incorrect, as that is interacting with the CastingServer.
Additionally, the cancelDiscoveryCommissionersWork needs to be cleaned up (canceled, nil'ed) when stopMatterServer is called.
Initialized the chipWorkQueue earlier, in the CastingServerBridge.init(), and dispatched cancelDiscoveryCommissionersWork on the chipWorkQueue instead.
Tested with the iOS tv-casting-app

iOS tv-casting-app: cancelDiscoveryCommissionersWork should be dispatched on the chipWorkQueue (not clientQueue)

---

examples/tv-casting-app/APIs.md

This PR contains the developer docs for a simplified version of the Matter TV Casting library APIs that we are planning to move to (from the existing CastingServerBridge/TvCastingApp implementations) based on our learnings so far. This is expected to simplify onboarding of a new casting app to the Matter Casting library and also reduce maintenance overhead on the library itself.

TV Casting API docs

---

zzz_generated/tv-casting-app/zap-generated/gen_config.h

If the tv-casting-app is commissioned by many Matter TVs, it seems it can run out of space in the Binding table that is cached on disk. This leads to issues during commissioning where the app does not find a nodeId corresponding to a fabricIndex because the binding table overflowed.
Increased EMBER_BINDING_TABLE_SIZE from 10 to 64
Built and tested with the iOS tv-casting-app against the Linux tv-app

tv-casting-app: Increasing EMBER_BINDING_TABLE_SIZE from 10 to 64

---

examples/tv-casting-app/android/App/app/src/main/jni/com/chip/casting/TvCastingApp.java
examples/tv-casting-app/tv-casting-common/include/CastingServer.h
examples/tv-casting-app/tv-casting-common/src/CastingServer.cpp

The IPAddress and MACAddress fields (in the TargetVideoPlayerInfo), required for the WakeOnLAN implementation, were sometimes getting corrupted when the VerifyOrEstablishConnectionTask() API is called. This was because the VerifyOrEstablishConnection() API gets a reference to the targetVideoPlayerInfo that is created on the stack by the caller. If we copy the input param targetVideoPlayerInfo to the mActiveTargetVideoPlayerInfo, the underlying memory for the IPAddress and MACAddress may get deallocated as the original targetVideoPlayerInfo goes out of scope of the caller.
Find the index of the targetVideoPlayerInfo in the mCachedTargetVideoPlayerInfo array that is held in the CastingServer class as a data member. Then copy the cached equivalent of the targetVideoPlayerInfo to …

tv-casting-app: fix TargetVideoPlayerInfo mem corruption
